# Generated by Django 2.2.7 on 2019-12-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='search',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'search',
                'managed': False,
            },
        ),
    ]
