# Generated by Django 2.2.7 on 2019-12-03 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20191202_2321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchlist',
            options={},
        ),
    ]
