# Generated by Django 2.2.7 on 2019-12-05 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20191203_2014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchlist',
            options={'managed': False},
        ),
    ]
